#%RAML 1.0 DataType
type: object
displayName: salesdataType
properties:
   Region:
     required: true
     type: string
     example: "Sub-Saharan Africa"
   Country:
     required: true
     type: string
     example: "Tanzania"
   ItemType:
     required: true
     type: string
     example: "Cosmetics"
   SalesChannel:
     required: true
     type: string
     example: "Offline"
   OrderPriority:
     required: true
     type: string
     example: "C"
   OrderDate:
     required: true
     type: string
     example: "4/3/2012"
   OrderID: 
     required: true
     type: integer
     example: 423403060
   ShipDate:
     required: true
     type: string
     example: "4/30/2012"
   UnitsSold:
     required: true
     type: string
     example: "3229"
   UnitPrice:
     required: true 
     type: string
     example: "437.20"
   UnitCost:
     required: true
     type: string
     example: "263.33"
   TotalRevenue:
     required: true
     type: string
     example: "1411718.80"
   TotalCost:
     required: true
     type: string
     example: "850292.57"
   TotalProfit:
     required: true
     type: string
     example: "561426.23"