#%RAML 1.0 NamedExample

value:
  Region: "Asia"
  Country: "India"
  ItemType: "hgh"
  SalesChannel: "Online"
  OrderPriority: "L"
  OrderDate: "01/01/2020"
  OrderID: 123456789
  ShipDate: "02/02/2020"
  UnitsSold: "12"
  UnitPrice: "1234"
  UnitCost: "4566"
  TotalRevenue: "456765"
  TotalCost: "89798"
  TotalProfit: "45678765"
  Commission:
    orderID: 12345678
    commission: 2323.45
